#!/bin/sh
echo "{ .titan }"

OLEM=~olem
test -d "$OLEM/bin" && append_path PATH "$OLEM/bin"

alias sq='squeue -u dmheggo -o "%.7i %.8j %.3t %.10M %.10l %.6D %.6C %R"'

# Sync
#cd synced
#git pull
#cd

# Python
source /site/Modules/default/init/bash 
#source /xanadu/share/etc/modules.default 
module load local

# Python 2.4 -> 2.6:
module load python

# ASE:
#export PYTHONPATH=/usit/titan/u1/friisj/usr/lib64/python2.6/site-packages:$PYTHONPATH

export PYTHONPATH=/usit/titan/u1/dmheggo/python:$PYTHONPATH


#------------------------------------------------------------------------
# this is for XCRYSDEN 1.5.21; added by XCRYSDEN installation on
# Tue Nov 30 21:56:09 CET 2010
#------------------------------------------------------------------------
XCRYSDEN_TOPDIR=/usit/titan/u1/dmheggo/opt/XCrySDen-1.5.21-bin-semishared
XCRYSDEN_SCRATCH=/usit/titan/u1/dmheggo/xcrys_tmp
export XCRYSDEN_TOPDIR XCRYSDEN_SCRATCH
PATH="$XCRYSDEN_TOPDIR:$PATH:$XCRYSDEN_TOPDIR/scripts:$XCRYSDEN_TOPDIR/util"


