#!/usr/bin/env python

import argparse
from mwclient import Site
import sys

def init_argparse() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Fetch a mediawiki PAGE from SITE."
    )
    parser.add_argument('site', nargs=1)
    parser.add_argument('pages', nargs='+')
    return parser


def main() -> None:
    parser = init_argparse()
    args = parser.parse_args()
    site_name = args.site[0] + '.wikipedia.org'
    site = Site(site_name)

    for page_name in args.pages:
        sys.stderr.write('Fetching %s\n' % page_name)
        page_text = site.pages[page_name].text()

        if ':' in page_name:
            ns, page_name = page_name.split(':', 1)
        else:
            ns = ''
        page_name = page_name.replace(':', '_').replace('/', '_')
        if ns == 'Module':
            filename = page_name + '.lua'
        else:
            filename = page_name + '.wiki'
        with open(filename, 'w', encoding='utf-8') as fp:
            fp.write(page_text)
        sys.stderr.write('Saved as %s\n' % filename)


if __name__ == '__main__':
    main()